version: "3.7"

services:
    flask:
        build:
            context: ./app
            dockerfile: Dockerfile
        container_name: flask
        restart: always
        expose:
            - 8080
        volumes:
            - ./app/:/app

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: nginx
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/000-default.conf
            - ./logs/:/var/log/nginx
